Doc c api clarify
wasmerio/wasmer pull request #2083
Opened 2021-02-01 10:51 UTC by Hywan

# Description

As suggested in https://github.com/wasmerio/wasmer/pull/2053#discussion_r566692725, this PR removes the automatically generated documentation when building `wasmer_wasm.h`.

It also clarifies our position regarding stability, and add a section about the documentation.

# Review

- [ ] Add a short description of the the change to the CHANGELOG.md file

2021-02-01 14:06 UTC, jubianchi requested changes

2021-02-01 14:06 UTC, jubianchi commented on lib/c-api/src/wasm_c_api/wasi/mod.rs
> +/// cbindgen:prefix=DEPRECATED("This function is longer necessary. You may safely remove all calls to it and everything will continue to work.")
```suggestion
/// cbindgen:prefix=DEPRECATED("This function is no longer necessary. You may safely remove all calls to it and everything will continue to work.")
```

2021-02-01 14:11 UTC, jubianchi approved these changes

2021-02-01 14:12 UTC, Hywan commented
bors r+

2021-02-01 14:22 UTC, MarkMcCaskey approved these changes

2021-02-02 07:50 UTC, Hywan commented
bors r+

2021-02-02 08:25 UTC, Hywan commented
bors r+

2021-02-02 09:24 UTC, Hywan commented
bors r+

2021-02-02 10:04 UTC, merged