doc: Improve `README.md`
wasmerio/wasmer pull request #2365
Opened 2021-05-31 14:27 UTC by Hywan

# Description

This PR improves our `README.md`.

* The “main” one has a better description of what Wasmer is by giving the keywords in the first sentence. It also lists more way to install Wasmer CLI. It removes the use of `<quote />` to indicate a note, it's semantically invalid. It explains super quickly the notion of compilers and engines by using the words “compilation strategies” and “artifact strategies”. And more.
* WIP

# Review

- [ ] Add a short description of the change to the CHANGELOG.md file

2021-05-31 19:48 UTC, jubianchi requested changes

2021-06-01 07:26 UTC, Hywan commented on README.md
> +* **Universal**. You can run Wasmer in any _platform_ (Linux, macOS
:+1: thanks!

2021-06-01 07:26 UTC, Hywan commented on README.md
> +    scopp install wasmer
:+1: thanks! good eyes!

2021-06-01 09:27 UTC, Hywan commented
If everyone agrees on the new `/README.md`, we should then update the translations.

2021-06-01 14:35 UTC, jubianchi approved these changes

2021-06-01 14:35 UTC, jubianchi commented on SECURITY.md
> +| 1.x | ✅ |
We should add the 2.x here I think

2021-06-01 17:48 UTC, Hywan commented on SECURITY.md
> +| 1.x | ✅ |
Not yet. It's not released :-).

2021-06-01 17:48 UTC, Hywan commented
bors r+

2021-06-01 18:28 UTC, merged

2021-06-02 02:34 UTC, syrusakbary commented
I ended refactoring again the main README. It was optimized for readability and being concise in propose.
However, there are a few things that you did improve in the right direction. So I just went a step forward on it!

Note: we did use `<quote>` because how it renders on Github, not because it was semantically valid.

Here's before: https://github.com/wasmerio/wasmer/tree/5f46b9dd260fe1c6fd1c7d46b0d887daacc0e6c2
Here's after: https://github.com/wasmerio/wasmer/tree/d2e22d6ea572e4a76813ede70a69119dfa0aaa79