c-api: add functions to overwrite stdin and to write to it [WIP]
wasmerio/wasmer pull request #3032
Opened 2022-07-21 11:46 UTC by epilys

Fixes #2334

# Review

- [ ] Add functional test for this **(important!)**
- [ ] Add a short description of the change to the CHANGELOG.md file

2022-08-05 10:19 UTC, fschutt commented
@epilys as you requested, I separated the fixes from clippy and `make lint` into a new PR, which can be merged after this PR has been merged. The other tests should work, so this PR can be merged now.

[patches.zip](https://github.com/wasmerio/wasmer/files/9267750/patches.zip)

2022-08-05 10:50 UTC, epilys commented
@syrusakbary this needs a manual merge as well

2022-08-05 10:57 UTC, syrusakbary requested changes
I think we may need a meeting to discuss this further. I see as an issue that we are operating just in terms of specific structs (STDIN, STDOUT, STDERR), rather than in terms of pipes.

I'd like the API to be pipe based, as I think it will be more resilient also for other kind of filesystem things. Let's discuss

2022-08-05 11:00 UTC, fschutt commented
You can store pipe objects inside of the structs, the current approach is much more flexible than locking the approach to pipes. I could add code to add a `wasi_new_console_out_pipe()` to use pipes, if you want, but I wouldn't change the overall API.

2022-08-18 11:17 UTC, syrusakbary commented on lib/c-api/src/wasm_c_api/wasi/mod.rs
> +    alignof: usize,        /* = alignof(Pipe) */
We can delete this

2022-08-18 11:18 UTC, syrusakbary commented on lib/c-api/src/wasm_c_api/wasi/mod.rs
> +    ptr: *const c_void,    /* = *Pipe */
Why don't we have directly: `ptr: *mut Pipe`

2022-08-18 11:20 UTC, syrusakbary commented on lib/c-api/src/wasm_c_api/wasi/mod.rs
> +    let ptr: &mut Pipe = &mut data;
This can be improved

2022-08-22 12:56 UTC, syrusakbary commented on lib/c-api/src/wasm_c_api/wasi/mod.rs
> +pub unsafe extern "C" fn wasi_console_out_new_memory() -> *mut wasi_console_out_t {
`wasi_pipe_new`

2022-08-24 11:56 UTC, closed without merging