Remove assert in sse_round_fn and handle case where src2 is in memory
wasmerio/wasmer pull request #3465
Opened 2023-01-10 10:43 UTC by sydhds

In Singlepass SSE4.2 backend and for sse_round_fn function, some special cases were not handled:
* src1 != src2
* src2 is in memory

This should fix those cases.

This is a follow up of ticket https://github.com/wasmerio/wasmer/issues/3461

2023-01-10 10:58 UTC, ptitSeb commented on lib/compiler-singlepass/src/emitter_x64.rs
> +                    move_src_to_dst(emitter, precision, x, dst);
No like this.
You need to create an `if src1 == x` with that new code, and have the old code in the `else` branch.

2023-01-10 10:59 UTC, ptitSeb requested changes
Please create a `if` /  `else` branch

2023-01-10 13:56 UTC, ptitSeb requested changes
So, I reviewed the ROUNDSS/VROUNDSS opcode (for example, it's one of the opcode use here): https://www.felixcloutier.com/x86/roundss
And it's not what I imagined.
So the code should be:
```rust
if x != dst {
 move_src_to_dst(emitter, precision, src1, dst);
}
dynasm!(emitter ; $ins Rx((x as u8)), Rx((dst as u8)), $mode)
```
Basicaly a bigger change, but that version should be exact. It's not important for now, as ROUND functions are basically used as 2 operators opcode, never as 3-way in Singlepass.

2023-01-10 20:20 UTC, ptitSeb approved these changes

2023-01-11 09:34 UTC, syrusakbary approved these changes
It should already be approved. But approving again to see if that trigger tests

2023-01-19 22:07 UTC, merged

2023-01-19 22:08 UTC, syrusakbary commented
Merged manually, as I had no idea why tests are not being executed

2023-01-19 22:11 UTC, theduke commented
@syrusakbary Github Actions have been problematic the last two days, also on other repos.
Timeouts, network errors, jobs just sitting idle forever, ...