C API: u8 in Rust corresponds to unsigned char* in C
wasmerio/wasmer pull request #3597
Opened 2023-02-21 12:31 UTC by dannywillems

# Description

wasm_memory_data returns type is [*mut u8](https://github.com/wasmerio/wasmer/blob/c9e658e25e4a4d915ef2663188360751125a095a/lib/c-api/src/wasm_c_api/externals/memory.rs#L65) which corresponds in C to `unsigned char *`. `byte_t` is used in the C API to represent `*mut u8` but it is an [alias for char](https://github.com/wasmerio/wasmer/blob/c9e658e25e4a4d915ef2663188360751125a095a/lib/c-api/tests/wasm-c-api/include/wasm.h#L37).
When compiling, we get the following warning:
```
warning: pointer targets in initialization of ‘uint8_t *’ {aka ‘unsigned char *’} from ‘byte_t *’ {aka ‘char *’} differ in signedness [-Wpointer-sign]
  572 |    uint8_t* x420 = wasm_memory_data(x419);
```

This MR changes the return type from `byte_t` to `unsigned char`.

2023-02-21 13:12 UTC, ptitSeb approved these changes

2023-02-21 13:12 UTC, ptitSeb commented
Ah yes, good catch.

2023-02-21 13:14 UTC, dannywillems commented
I would suggest to add the flags `-Wall -Wextra` in the tests.

2023-02-23 21:15 UTC, syrusakbary commented
We can't move from the standard `wasm.h` headers or used types.

If you want to change the `wasm.h` header file, I'd suggest making it a PR to the main `wasm-c-api` repo:
https://github.com/WebAssembly/wasm-c-api/blob/main/include/wasm.h#L478

2023-02-23 21:16 UTC, syrusakbary requested changes
We can't merge this as this file is just a mirror of:
https://github.com/WebAssembly/wasm-c-api/blob/main/include/wasm.h#L478

2023-02-23 22:49 UTC, dannywillems commented
> We can't merge this as this file is just a mirror of: https://github.com/WebAssembly/wasm-c-api/blob/main/include/wasm.h#L478

See https://github.com/WebAssembly/wasm-c-api/pull/179

2024-03-05 09:43 UTC, syrusakbary commented
Closing this as stale, but feel free to reopen the PR once wasm-c-api merges this upstream

2024-03-05 09:43 UTC, closed without merging