Warn on email not validated
wasmerio/wasmer pull request #4080
Opened 2023-07-14 07:34 UTC by Michael-F-Bryan

This fixes #4079 by checking the `isEmailVerified` field when looking up information about the current user. If the email address isn't verified, commands like `wasmer whoami` and `wasmer login` will print a warning message.

2023-07-14 07:46 UTC, ayys commented on lib/cli/src/commands/whoami.rs
> +                    println!("Warning: Your email address still needs to be verified");
```suggestion
                    eprintln!("Warning: Please verify your email address to fully access all Wasmer features");
```

I am not familiar with the codebase so maybe using eprintln isn't the right way? idk, just a suggestion.

2023-07-14 08:40 UTC, dynamite-bud requested changes

2023-07-14 08:40 UTC, dynamite-bud commented on lib/cli/src/commands/login.rs
> +                            println!("Warning: Please verify your email address to fully access all Wasmer features");
@Michael-F-Bryan If the person is not verified he can't create the tokens too. So he should not be able to login. And if he's not verified he also can't proceed with the login again path probably with that same account. In the case of person not being verified the login should just stop ?

2023-07-14 08:54 UTC, dynamite-bud commented on lib/cli/src/commands/login.rs
> +                            println!("Warning: Please verify your email address to fully access all Wasmer features");
@Michael-F-Bryan Okay this thing has been redacted by @syrusakbary. Only warning will suffice

2023-07-17 08:31 UTC, dynamite-bud commented on lib/cli/src/commands/login.rs
> +                            println!("Warning: Please verify your email address to fully access all Wasmer features");
As discussed, this behaviour is required and we want the person to be able to create tokens even not verified to improve the DX but show a warning like this.

2023-07-17 08:32 UTC, dynamite-bud approved these changes
Looks Good @Michael-F-Bryan

2023-12-08 14:06 UTC, closed without merging

2023-12-08 14:06 UTC, Michael-F-Bryan commented
It turns out email validation wasn't necessary. From memory, it wasn't possible to get into a situation where the CLI is logged in but your email hasn't been validated.