Ability to detect a tainted instance
wasmerio/wasmer pull request #4220
Opened 2023-09-18 03:03 UTC by john-sharratt

This needs to go in first
https://github.com/wasmerio/wasmer/pull/4211

2023-09-18 12:43 UTC, theduke approved these changes

2023-09-19 23:04 UTC, Michael-F-Bryan requested changes
You'll generally want to share a `Runtime` to reuse the same thread pool, any connections that may still be held open by the HTTP client, in-memory caches, and so on.

With that in mind, I think we need to include some sort of ID (or a reference to the `wasmer::Instance`) in `on_taint()` that allows the runtime to know *which* instance became tainted. Otherwise we've just got a *"something went wrong"* callback and the only way to know which instance became tainted is through context, which is pretty brittle.

2024-03-05 09:59 UTC, syrusakbary commented
We'll keep this open for now, but ideally we should use proper signal propagation to implement this properly (based on @theduke feedback)

2024-03-12 15:47 UTC, theduke approved these changes

2024-03-12 18:10 UTC, merged