replace mach with mach2
wasmerio/wasmer pull request #4250
Opened 2023-10-11 08:42 UTC by Arshia001

Closes #4222.

Note, since `mach` was also being used by `region`, I had to fork and patch `region` too. The patch can be removed once the changes are merged upstream and released.

2023-10-11 10:17 UTC, syrusakbary requested changes
This is great, but we can't merge this upstream until the dependencies are in crates.io (as otherwise we can't publish wasmer to crates.io)

2023-10-11 11:00 UTC, Arshia001 commented
Yes, I realised a few minutes too late that that this is not a wasix app 😄

Gonna have to create a PR in region and hope they accept and publish a new version.

2023-11-02 12:37 UTC, theduke commented
@Arshia001 what's the status here?

2023-11-02 12:39 UTC, Arshia001 commented
@theduke we still need to open a PR in `region`.

2024-01-09 10:14 UTC, syrusakbary commented
Solution: create region2 create with the fix

2024-06-20 08:01 UTC, closed without merging