Manage DNS records
wasmerio/wasmer pull request #4487
Opened 2024-03-13 21:55 UTC by ayys

This adds subcommands to manage domains and DNS records.
This PR gives you the ability to list, get, and sync zone files for domains.

``` shell
$ wasmer domains list # list all domains

$ wasmer domains list <namespace> # list all domains in the namespace

$ wasmer domain get <domain-name>

$ wasmer domain get-zone-file <domain-name>

$ wasmer domain sync-zone-file <zone-file> [--no-delete-missing-records]
```

2024-03-14 08:52 UTC, theduke requested changes

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/commands/domain/get.rs
> +            println!("Domain not found");
Return error so the command fails with a non-zero exit code.

Eg: `anyhow::bail!("Domain not found");`

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/commands/domain/get.rs
> +        Ok(())
We probably want to fail with a not found error here.

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/commands/domain/list.rs
> +        let domains = domains_connection
We can leave this for later, but this will need pagination / a --all flag to fetch all domains.

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/commands/domain/zonefile.rs
> +        required = false,
Neither required nor default_valueis required here, these are automatic.

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/commands/domain/zonefile.rs
> +                std::fs::write(zone_file_path, zone_file_contents).expect("Unable to write file");
Don't use expect, return the error instead.

Hint: you can use `.context("unable ...")?`, (you need to import `use anyhow::Context` first)

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/commands/domain/zonefile.rs
> +            println!("Domain not found");
Return error ( eg `anyhow::bail!("Domain not found)`)

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/commands/domain/list.rs
> +                edge.expect("domain not found")
No `.expect()`, need to return an error instead.

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/commands/domain/zonefile.rs
> +        let data = std::fs::read(&self.zone_file_path).expect("Unable to read file");
No `.expect()`.

2024-03-14 08:52 UTC, theduke commented on lib/cli/src/types.rs
> +                    record.name().expect("Expected record name").to_string(),
No `.expect()`, use a stub value instead , eg `.unwrap_or_else(|| "<no name>".to_string()`

2024-03-14 08:52 UTC, theduke commented on lib/backend-api/src/query.rs
> +        .run_graphql_raw(types::UpsertDomainFromZoneFile::build(vars))
Should use `.run_graphql_strict()` here to fail on any returned GraphQL errors.

2024-03-18 11:43 UTC, ayys commented on lib/cli/src/opts.rs
> +pub struct ItemTableFormatOpts {
Resolved on slack: https://wasmerio.slack.com/archives/C03MX4KL6KH/p1710759045973139?thread_ts=1710758497.967439&cid=C03MX4KL6KH

2024-03-18 11:56 UTC, theduke approved these changes

2024-03-18 12:00 UTC, syrusakbary approved these changes

2024-03-18 13:03 UTC, merged