add proxy support to the `package download` subcommand
wasmerio/wasmer pull request #4640
Opened 2024-05-06 19:59 UTC by maminrayej

In continuation with #4624, this PR adds proxy support to the `wasmer package download` subcommand.

2024-05-07 09:00 UTC, syrusakbary commented on lib/cli/src/commands/package/download.rs
> +        };
We need to abstract this into a common function that is reused

2024-05-07 09:00 UTC, syrusakbary requested changes
Address comment

2024-05-07 09:31 UTC, ayys commented
Potential future changes: we will probably need to do the same for wasmer run (I think that uses a different code path to download the package).
Also, the code to upload file to google storage would also break I suppose? so we will need to add proxy there as well. (cc: @xdoardo since he is working on the publish stuff)

2024-05-07 10:15 UTC, maminrayej commented
> Potential future changes: we will probably need to do the same for wasmer run (I think that uses a different code path to download the package).

The code path for `wasmer run` was covered in #4624 .

> Also, the code to upload file to google storage would also break I suppose? so we will need to add proxy there as well

That's a good point. I can check that code path as well.

2024-05-09 09:23 UTC, syrusakbary commented on lib/wasix/src/http/reqwest.rs
> +
We can have a function.

```rust
fn get_proxy(): Result<reqwest::Proxy> {
    let proxy = env::var("http_proxy").or_else(|_| env::var("HTTP_PROXY")).map(reqwest::Proxy::all(scheme))
}
```

2024-05-09 09:23 UTC, syrusakbary approved these changes
Approved once comment is addressed

2024-05-09 15:21 UTC, merged