Add option for using webc v3
wasmerio/wasmer pull request #4651
Opened 2024-05-08 16:43 UTC by maminrayej

This PR adds support for the `USE_V3` env var. If set, the cli will download `v3` version of a package.

2024-05-08 16:59 UTC, ayys commented
btw I'd call the env var `WASMER_USE_WEBCV3`

2024-05-08 17:13 UTC, maminrayej commented
> btw I'd call the env var `WASMER_USE_WEBCV3`

You're right. That's better.

2024-05-09 09:19 UTC, syrusakbary commented on lib/wasix/src/runtime/resolver/wapm_source.rs
> +        if std::env::var("WASMER_USE_WEBCV3").is_ok() {
This needs to be a configuration variable that is passes to WASIX. WASIX should NOT access env vars, only the CLI should

2024-05-09 09:19 UTC, syrusakbary submitted a review, later dismissed
Address env var comment

2024-05-09 10:12 UTC, theduke requested changes

2024-05-09 13:24 UTC, syrusakbary commented on lib/cli/src/commands/run/mod.rs
> +        let preffered_webc = match std::env::var("WASMER_USE_WEBCV3") {
This naming has a typo (two f's)... also I think we can use `preferred_webc_version` which is a bit more descriptive

2024-05-09 13:25 UTC, syrusakbary commented on lib/cli/src/commands/run/wasi.rs
> +        preffered_webc: webc::Version,
```suggestion
        preferred_webc_version: webc::Version,
```

2024-05-09 13:25 UTC, syrusakbary commented on lib/wasix/src/runtime/resolver/wapm_source.rs
> +    preffered_webc: webc::Version,
```suggestion
        preferred_webc_version: webc::Version,
```

2024-05-09 13:26 UTC, syrusakbary commented on lib/cli/src/commands/run/wasi.rs
> +            .with_prefferred_webc(preffered_webc);
```suggestion
            .with_preferred_webc_version(preffered_webc);
```

2024-05-09 13:26 UTC, syrusakbary commented on lib/wasix/src/runtime/resolver/wapm_source.rs
> +    preffered_webc: webc::Version,
```suggestion
    preferred_webc_version: webc::Version,
```

2024-05-09 13:26 UTC, syrusakbary commented on lib/wasix/src/runtime/resolver/wapm_source.rs
> +        if preffered_webc == webc::Version::V3 {
Improve naming

2024-05-09 13:26 UTC, syrusakbary commented on lib/wasix/src/runtime/resolver/wapm_source.rs
> +    preffered_webc: webc::Version,
Improve naming

2024-05-09 15:46 UTC, syrusakbary approved these changes

2024-05-09 15:56 UTC, merged