CLI: Use a channel to signal that the main fn is done
wasmerio/wasmer pull request #4860
Opened 2024-06-17 13:32 UTC by xdoardo

Tries to solve #4859. Use a channel to notify the `setup` thread that the main CLI function (`deploy`, `tag`, `push`..) is done and, in this case, should not wait for SIGINT to be received. Another approach could be that of simply calling `.abort()` on the `JoinHandle`.

2024-06-18 07:50 UTC, syrusakbary approved these changes
I think it will be better for @theduke to review it

2024-06-18 23:06 UTC, theduke requested changes

2024-06-18 23:06 UTC, theduke commented on lib/cli/src/commands/mod.rs
>              AsyncCliCommand::run_async(self).await?;
If an error is returned, this fails to trigger the shutdown channel.

2024-06-20 07:55 UTC, theduke approved these changes

2024-06-20 09:15 UTC, merged