Fix --entrypoint not working for WASI(X) modules
wasmerio/wasmer pull request #5107
Opened 2024-09-23 15:51 UTC by Arshia001

This closes #4691.

2024-09-23 15:58 UTC, xdoardo approved these changes

2024-09-23 16:18 UTC, syrusakbary requested changes
I think there's misunderstanding on what entrypoint is for.

Entrypoint is used for calling a specific command inside of webc. Basically, it needs to be a command inside of a package. Not a function inside of wasm.

For a function inside of wasm we should have (if we don't have already) an `--invoke` flag in the cli

2024-09-23 16:22 UTC, Arshia001 commented
@syrusakbary my understanding is that, for pure WASM modules, the entrypoint flag specifies a function inside the module which is to be invoked: https://github.com/wasmerio/wasmer/blob/d11fccdd74cfba48ac3cad78a58a343a611e3f6b/lib/cli/src/commands/run/mod.rs#L380-L390

Considering that this code deals with running a single WASIX module (as opposed to an entire webc) I'd say the code is consistent with what was already there.

2024-09-24 08:26 UTC, Arshia001 commented
@syrusakbary Please review again

Note: this is a breaking change, and should be merged only for 5.0.

2024-09-24 09:44 UTC, syrusakbary approved these changes

2024-09-24 09:52 UTC, merged