fix: pass readme content instead of readme file name
wasmerio/wasmer pull request #5292
Opened 2024-12-09 20:40 UTC by ayys

the readme field in wasmer.toml is supposed to be a pathbuf, but it is
being passed to the backend as a string. This should be the content
of the readme file, and not the file path itself.

the commit fixes this by reading the file, and passing the content
correctly.

2024-12-10 10:48 UTC, xdoardo approved these changes

2024-12-10 10:53 UTC, syrusakbary approved these changes

2024-12-10 14:28 UTC, syrusakbary commented on lib/cli/src/commands/package/tag.rs
> +                let readme_path = Path::new(&readme);
This path has to be relative to where the manifest lives. I don't think we are accounting for that on this code

2024-12-10 14:28 UTC, syrusakbary requested changes
Please address last comment

2024-12-12 08:40 UTC, syrusakbary approved these changes

2024-12-12 08:40 UTC, merged